config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }
  root to: 'tests#index'
  resources :tests, only: :index do
    member do
      post :start
    end
  end
  resources :test_passages, only: [:show, :update] do
    member do
      get :result
      post :gist
    end
  end
  resources :feedbacks, only: [:new, :create]
  resources :badges, only: :index

  namespace :admin do
    resources :gists, only: :index
    resources :badges
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: [:index, :show]
      end
    end
  end
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_and_belongs_to_many :users
  belongs_to :badge_rule

  validates :title, presence: true
  validates :image, presence: true
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :find_badge, only: [:show, :edit, :update, :destroy]

  def index
    @badges = Badge.all
  end

  def show
  end

  def new
    @badge = Badge.new
  end

  def edit
  end

  def create
    @badge = Badge.new(badge_params)
    if @badge.save
      redirect_to admin_badges_path, notice: t('.success')
    else
      render :new
    end
  end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badges_path
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  private

  def find_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:title, :image, :badge_rule_id)
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :authenticate_user!

  def index
    @badges = current_user.badges
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/admin/badges/_badge.html.slim
.col-2
  = image_tag(badge.image, class: 'fit')
  p = badge.title
  p = link_to t("application.link.edit"), edit_admin_badge_path(badge)

app/views/admin/badges/_form.html.slim
= form_for [:admin, @badge], local: true do |f|
  = render 'errors', object: @badge
  p
    = f.label :title
    = f.text_field :title, class: 'form-control mr-2'
  p
    = f.label :image
    = f.text_field :image, class: 'form-control mr-2'
  p
    = f.label :image
    = f.text_field :image, class: 'form-control mr-2'
  = f.submit t('.submit'), class: 'btn btn-primary'

app/views/admin/badges/edit.html.slim
.row.justify-content-center.mt-4
  .col.col-md-6
    h1.mb-4 = t('.header')
    = render 'form'

app/views/admin/badges/index.html.slim
.row.mt-4.mb-4
  .col
    h1 = t('.header')
.row
  = render @badges
.row
  .col
    hr
    = link_to t('.add_new'), new_admin_badge_path, class: 'btn btn-primary'

app/views/admin/badges/new.html.slim
.row.justify-content-center.mt-4
  .col.col-md-6
    h1.mb-4 = t('.header')
    = render 'form'